linters-settings:
  custom:
    argument_checker:
      path: ./plugins/argument_checker.so
      description: argument_checker is checking if the first argument of query and command interface function is context.Context.

linters:
  disable-all: true
  enable:
    - argument_checker
    - typecheck
