linters-settings:
  govet:
    check-shadowing: true
  custom:
    argument_checker:
      path: .plugins/argument_checker.so
      description: argument_checker is checking terms of snkrdunk.com.

linters:
  disable-all: true
  enable:
    - argument_checker
    - typecheck
    - govet
