name: Set skip-server-test
description: Add skip-server-test=true variable to output if changes are only in the frontend directory

inputs:
  changed_files:
    description: "List of changed files"
    required: true
    type: string

outputs:
  skip-server-test:
    description: "skip-server-test flag variable"
    value: ${{ steps.set.outputs.skip-server-test }}

runs:
  using: "composite"
  steps:
    - id: set
      name: Set skip-server-test to output
      shell: bash
      run: |
        skip_server_test=true
        
        for file in ${{ inputs.changed_files }}; do
          echo $file;
          if [[ $file != frontend/* ]]; then
            skip_server_test=false
            break
          fi
        done
        
        echo "skip-server-test=$skip_server_test" >> ${GITHUB_OUTPUT}
