name: Skip Server Test for Frontend Changes
description: Add SKIP_SERVER_TEST=true environment variable if changes are only in the frontend directory

outputs:
  skip-server-test:
    description: "SKIP_SERVER_TEST environment variable"
    value: ${{ steps.set.outputs.SKIP_SERVER_TEST }}
    default: "false"

runs:
  using: "composite"
  steps:
    - id: set
      name: Set SKIP_SERVER_TEST environment variable
      if: ${{ github.event_name == 'pull_request' }}
      shell: bash
      run: |
        git fetch origin ${{ github.base_ref }}

        git branch
        
        skip_server_test=true
        
        for file in $(git diff origin/${{ github.base_ref }} --name-only); do
          echo $file;
          if [[ $file != frontend/* ]]; then
            break
          fi
        done

        echo "SKIP_SERVER_TEST=$skip_server_test" >> $GITHUB_OUTPUT
