name: Skip Server Test for Frontend Changes
description: Add SKIP_SERVER_TEST=true environment variable if changes are only in the frontend directory

runs:
  using: "composite"
  steps:
    - name: Check for frontend changes
      shell: bash
      run: |
        echo "マージ先のコミットログ${{ github.event.pull_request.base.sha }}"
        skip_server_test=true
        for file in $(git diff --name-only ${{ github.event.pull_request.base.sha }}...${{ github.sha }}); do
          echo $file;
          if [[ $file != frontend/* ]]; then
            skip_server_test=false
            break
          fi
        done

        echo "SKIP_SERVER_TEST=$skip_server_test" >> $GITHUB_ENV
