name: Set skip-server-test
description: Add skip-server-test=true variable to output if changes are only in the frontend directory

outputs:
  skip-server-test:
    description: "skip-server-test flag variable"
    value: ${{ steps.set.outputs.skip-server-test }}

runs:
  using: "composite"
  steps:
    - id: set
      name: Set skip-server-test to output
      if: ${{ github.event_name == 'pull_request' }}
      shell: bash
      run: |
        git fetch origin ${{ github.base_ref }}

        skip_server_test=true
        
        for file in $(git diff --name-only origin/${{ github.base_ref }}...origin/${{ github.head_ref }}); do
          echo $file;
          if [[ $file != frontend/* ]]; then
            skip_server_test=false
            break
          fi
        done
        
        echo "skip-server-test=$skip_server_test" >> ${GITHUB_OUTPUT}
