name: Set skip-server-test
description: Add skip-server-test=true variable to output if changes are only in the frontend directory

outputs:
  skip-server-test:
    description: "skip-server-test flag variable"
    value: ${{ steps.set.outputs.skip-server-test }}

runs:
  using: "composite"
  steps:
    - id: changed-files
      name: Get changed files
      uses: tj-actions/changed-files@v44
    
    - id: set
      name: Set skip-server-test to output
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      shell: bash
      run: |
        skip_server_test=true
        
        for file in $(${{ env.ALL_CHANGED_FILES }}); do
          echo $file;
          if [[ $file != frontend/* ]]; then
            skip_server_test=false
            break
          fi
        done
        
        echo "skip-server-test=$skip_server_test" >> ${GITHUB_OUTPUT}
