name: check-env
on:
  push:
    branches:
      - main
jobs:
  check-skip-server-test:
    name: Check if the modification is for the front only
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.0.0
      
      - name: Use Skip Server Test action
        uses: ./.github/actions/set-env
      
      - name: check env
        run: echo "${{ env.SKIP_SERVER_TEST }}"
      
      - name: Set skip server test env
        run: echo "skip-server-test"="${{ env.SKIP_SERVER_TEST }}" >> "$GITHUB_OUTPUT"
  
  check:
    name: check
    runs-on: ubuntu-22.04
    if: ${{ needs['check-skip-server-test'].outputs.skip-server-test != 'true' }}
    steps:
      - uses: actions/checkout@v4.0.0
      - name: Check
        run: echo "Check"
