name: check-env
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-skip-server-test:
    name: Check if the modification is for the front only
    runs-on: ubuntu-22.04
    outputs:
      skip-server-test: ${{ steps.set-skip-server-test.outputs.skip-server-test }}
    steps:
      - uses: actions/checkout@v4.0.0

      - id: set-skip-server-test
        if: ${{ github.event_name == 'pull_request' }}
        name: Use Skip Server Test action
        uses: ./.github/actions/set-env

  check:
    needs: check-skip-server-test
    if: ${{ needs.check-skip-server-test.outputs.skip-server-test != 'true' }}
    name: check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.0.0
      
      - name: Check
        run: |
          echo "skip-server-test is ${{ needs.check-skip-server-test.outputs.skip-server-test }}"

  check2:
    needs: check
    name: check2
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        target: ["batch","cache-updater","internal","localstack","mysql","mysql-v8","schemaspy","server","worker","worker-sqs"]
        exclude:
          - target: localstack
    steps:
      - uses: actions/checkout@v4.0.0
      
      - name: Check
        run: |
          echo "check2"
