name: check-env
on:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  check-skip-server-test:
    name: Check if the modification is for the front only
    runs-on: ubuntu-22.04
    outputs:
      skip-server-test: ${{ steps.set-skip-server-test.outputs.SKIP_SERVER_TEST }}
    steps:
      - uses: actions/checkout@v4.0.0
      
      - id: set-skip-server-test
        name: Use Skip Server Test action
        uses: ./.github/actions/set-env
      
      - name: Check
        run: echo "結果 ${{ steps.set-skip-server-test.outputs.SKIP_SERVER_TEST }}"
  
  check:
    needs: check-skip-server-test
    if: ${{ needs.check-skip-server-test.outputs.skip-server-test }} != 'true'
    name: check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.0.0

      - name: Check1
        run: echo "${{ needs.check-skip-server-test.outputs}}"
      
      - name: Check
        run: echo "${{ needs.check-skip-server-test.outputs.skip-server-test }}"
