name: check-env
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-skip-server-test:
    name: Check if the modification is for the front only
    runs-on: ubuntu-22.04
    outputs:
      skip-server-test: ${{ steps.set-output.outputs.skip-server-test }}
      value1: ${{ steps.set-output.outputs.output1 }}
    steps:
      - uses: actions/checkout@v4.0.0
      
      - id: set-skip-server-test
        name: Use Skip Server Test action
        uses: ./.github/actions/set-env
      
      - id: set-output
        name: Check
        run: |
          echo "set-skip-server-test output ${{ env.SKIP_SERVER_TEST }}"
          echo "skip-server-test=${{ env.SKIP_SERVER_TEST }}" >> "$GITHUB_OUTPUT"
          echo "output1=value1" >> "$GITHUB_OUTPUT"

  check:
    needs: check-skip-server-test
    if: ${{ needs.check-skip-server-test.outputs.skip-server-test }} != 'true'
    name: check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.0.0
      
      - name: Check
        run: |
          echo "skip-server-test is ${{ needs.check-skip-server-test.outputs.skip-server-test }}"
          echo "value1 is ${{ needs.check-skip-server-test.outputs.value1 }}"
