name: go-lint
on:
  pull_request:
jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.5.2

      - name: Checkout custom_linters
        uses: actions/checkout@v3.5.2
        with:
          repository: snkrdunk/custom_linters
          path: custom_linters

      - uses: actions/setup-go@v4.0.1
        with:
          go-version-file: ./go.mod

      - name: Build plugins
        run: |
          go mod download
          go build -o '${{ github.workspace }}/.plugins/custom_linters.so' -buildmode=plugin ./plugin/main.go
        working-directory: ${{ github.workspace }}/custom_linters
        env:
          CGO_ENABLED: 1

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.1
          install-mode: goinstall
          args: --timeout 10m
          only-new-issues: true
          skip-pkg-cache: true
          skip-build-cache: true

