name: go-lint
on:
  pull_request:
jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.5.2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          args: --timeout 10m
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.51.2

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
