name: go-lint
on:
  pull_request:
jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.5.2
      
      - name: Check and get dependencies
        run: |
          go mod tidy
          git diff --exit-code go.mod
          go env

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53.3
          install-mode: goinstall
          args: --timeout 10m
          only-new-issues: true
      
      - name: check-golanci-lint-tools-version
        run: |
          go version -m /home/runner/go/bin/golangci-lint | grep golang.org/x/tools
