name: lint
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.REPOSITORYACCESSTOKENGENERATORAPPID }}
          private-key: ${{ secrets.REPOSITORYACCESSTOKENGNERATORSECRET }}
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ steps.app-token.outputs.token }}
