name: lint
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}
