name: test

on:
  push:
    branches:
      - test-*

env:
  ENV: dev

jobs:
  echo:
    runs-on: ubuntu-latest
    name: echo
    env:
      CURRENT_DATETIME: dev-$(date +'%Y%m%d%H%M%S')
    strategy:
      matrix:
        tag: dev-$(date +'%Y%m%d%H%M%S')
        target: [step1, step2, step3, step4]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Show current datetime
        run: |
          echo ${{ env.CURRENT_DATETIME }}
          echo ${{ env.ENV }}
          echo ${{ github.ref }}
          echo ${{ matrix.tag }}

  # notify:
  #   name: "push slack"
