name: test

on:
  push:
    branches:
      - test-*

jobs:
  echo:
    runs-on: ubuntu-latest
    name: echo

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set Environment Variables
        env:
          SHA: ${{ github.sha }}
        run: |
          echo ${SHA}
          echo ${SHA::15}

      - name: Echo
        run: |
          echo "ENV=$(echo ${{ github.ref }} | cut -d '/' -f 3 | cut -d '-' -f 1)" >> ${GITHUB_ENV}
          echo "TAG=$(echo ${{ github.ref }} | cut -d '/' -f 3)" >> ${GITHUB_ENV}
      
      - name: Echo ENV
        run: |
          echo ${{ env.ENV }}
          echo ${{ env.TAG }}

  # notify:
  #   name: "push slack"
