name: test

on:
  push:
    branches:
      - test-*

jobs:
  echo:
    runs-on: ubuntu-latest
    name: echo

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Echo
        run: |
          ENV=${{ github.ref }} | cut -d '/' -f 3 | cut -d '-' -f 1
          echo ${ENV}

  # notify:
  #   name: "push slack"
