name: test

on:
  push:
    branches:
      - dev-*

jobs:
  echo:
    runs-on: ubuntu-latest
    name: echo

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Echo
        run: |
          echo ${{ github.ref }}

  # notify:
  #   name: "push slack"
